"""Native declarative MolGFX bindings."""

from collections.abc import Sequence
from os import PathLike
from typing import Literal, Protocol, Self, final, overload

class _QueryLike(Protocol):
    @property
    def source(self) -> str: ...

_Target = str | _QueryLike
_Rgb = tuple[int, int, int]

@final
class ColorSpec:
    def legend_json(self) -> str | None: ...

_ColorLike = _Rgb | ColorSpec

@final
class ScalarExpr:
    def __add__(self, right: _ScalarLike, /) -> ScalarExpr: ...
    def __mul__(self, right: _ScalarLike, /) -> ScalarExpr: ...
    def clamp(self, minimum: float, maximum: float) -> ScalarExpr: ...
    def less(self, right: _ScalarLike) -> BoolExpr: ...

@final
class ScalarParameter:
    @property
    def name(self) -> str: ...
    @property
    def default(self) -> float: ...
    def expression(self) -> ScalarExpr: ...

_ScalarLike = float | ScalarExpr | ScalarParameter

@final
class VectorExpr:
    def __add__(self, right: _VectorLike, /) -> VectorExpr: ...
    def __mul__(self, right: _ScalarLike, /) -> VectorExpr: ...
    def normalized(self) -> VectorExpr: ...
    def dot(self, right: _VectorLike) -> ScalarExpr: ...

@final
class VectorParameter:
    @property
    def name(self) -> str: ...
    @property
    def default(self) -> tuple[float, float, float]: ...
    def expression(self) -> VectorExpr: ...

_VectorLike = tuple[float, float, float] | VectorExpr | VectorParameter

@final
class BoolExpr:
    def __and__(self, right: BoolExpr, /) -> BoolExpr: ...
    def __or__(self, right: BoolExpr, /) -> BoolExpr: ...
    def __invert__(self) -> BoolExpr: ...

_BoolLike = bool | BoolExpr

@final
class ColorExpr: ...

@final
class ColorParameter:
    @property
    def name(self) -> str: ...
    @property
    def default(self) -> _Rgb: ...
    def expression(self) -> ColorExpr: ...

_ColorExprLike = _Rgb | ColorExpr | ColorParameter

@final
class VisualStyle:
    def stable_hash(self) -> str: ...
    def explain(self) -> str: ...
    def wgsl(self) -> str: ...

class MolgfxError(Exception): ...
class SpecError(MolgfxError): ...
class RevisionConflict(MolgfxError): ...

@final
class Camera:
    def __new__(cls, *, position: tuple[float, float, float], target: tuple[float, float, float], up: tuple[float, float, float] = ..., fov_y: float | None = None, aspect: float = 1.0, near: float = 0.1, far: float = 10_000.0) -> Self: ...
    @property
    def position(self) -> tuple[float, float, float]: ...
    @property
    def target(self) -> tuple[float, float, float]: ...
    @property
    def up(self) -> tuple[float, float, float]: ...

@final
class Representation:
    def explain(self) -> str: ...
    def visual(self, style: VisualStyle) -> Representation: ...

@final
class SceneSpec:
    def __new__(cls, source: str) -> Self: ...
    @property
    def revision(self) -> int: ...
    def to_json(self) -> str: ...
    def stable_hash(self) -> str: ...
    def patched(self, patch: ScenePatch) -> SceneSpec: ...

@final
class ScenePatch:
    def __new__(cls, source: str) -> Self: ...
    @property
    def base_revision(self) -> int: ...
    def to_json(self) -> str: ...
    def inverse(self, base: SceneSpec) -> ScenePatch: ...

@final
class SceneTransaction:
    def __enter__(self) -> Scene: ...
    def __exit__(self, exception_type: object | None, exception: object | None, traceback: object | None) -> Literal[False]: ...

@final
class Scene:
    def __new__(cls, structure: object) -> Self: ...
    def add(self, representation: Representation) -> int: ...
    def set_visible(self, representation: int, visible: bool) -> None: ...
    def set_opacity(self, representation: int, opacity: float) -> None: ...
    def set_visual(self, representation: int, visual: VisualStyle | None) -> None: ...
    @overload
    def set_parameter(self, representation: int, parameter: ScalarParameter, value: float) -> None: ...
    @overload
    def set_parameter(self, representation: int, parameter: VectorParameter, value: tuple[float, float, float]) -> None: ...
    @overload
    def set_parameter(self, representation: int, parameter: ColorParameter, value: _Rgb) -> None: ...
    def focus(self, target: _Target) -> None: ...
    def set_camera(self, camera: Camera | None) -> None: ...
    def transaction(self) -> SceneTransaction: ...
    @overload
    def set_interaction(self, *, channel: Literal["selected", "hovered", "focused", "muted", "hidden"], target: _Target | None = None, name: None = None) -> None: ...
    @overload
    def set_interaction(self, *, channel: Literal["custom"], target: _Target | None = None, name: str) -> None: ...
    def apply(self, patch: ScenePatch) -> None: ...
    @property
    def revision(self) -> int: ...
    def to_json(self) -> str: ...
    @property
    def spec(self) -> SceneSpec: ...
    def explain(self) -> str: ...
    def _browser_sources(self) -> list[tuple[int, str, bytes]]: ...

@final
class Image:
    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...
    def png_bytes(self) -> bytes: ...
    def save(self, path: str | PathLike[str]) -> None: ...

@final
class PickResult:
    @property
    def kind(self) -> Literal["atom", "bond", "interaction", "label", "primitive", "mesh", "ligand_pose_batch", "guide", "dynamic_bond", "point", "instance", "template_part", "relation", "volume_segment"]: ...
    @property
    def dataset(self) -> int | None: ...
    @property
    def chunk(self) -> int | None: ...
    @property
    def row(self) -> int | None: ...
    @property
    def volume_label(self) -> int | None: ...

@final
class RenderProfile:
    @property
    def target_fps(self) -> int: ...
    @property
    def quality(self) -> Literal["auto", "interactive", "publication"]: ...

@final
class Renderer:
    def __new__(cls, *, profile: RenderProfile | None = None) -> Self: ...
    def render_image(self, scene: Scene, *, size: tuple[int, int]) -> Image: ...
    def pick(self, x: int, y: int) -> PickResult | None: ...
    def explain(self, scene: Scene) -> str: ...

class _Rep:
    def cartoon(self, *, target: _Target, style: Literal["ribbon", "rocket", "nucleic_acid", "glycan"] = "ribbon", width: float | None = None, opacity: float = 1.0, color: _ColorLike | None = None) -> Representation: ...
    def ball_and_stick(self, *, target: _Target, radius: float | None = None, bond_radius: float | None = None, opacity: float = 1.0, color: _ColorLike | None = None) -> Representation: ...
    def spacefill(self, *, target: _Target, radius: float | None = None, bond_radius: float | None = None, opacity: float = 1.0, color: _ColorLike | None = None) -> Representation: ...
    def licorice(self, *, target: _Target, radius: float | None = None, bond_radius: float | None = None, opacity: float = 1.0, color: _ColorLike | None = None) -> Representation: ...
    def lines(self, *, target: _Target, radius: float | None = None, bond_radius: float | None = None, opacity: float = 1.0, color: _ColorLike | None = None) -> Representation: ...
    def points(self, *, target: _Target, size: float | None = None, opacity: float = 1.0, color: _ColorLike | None = None) -> Representation: ...
    def surface(self, *, target: _Target, probe_radius: float | None = None, isolevel: float | None = None, opacity: float = 1.0, color: _ColorLike | None = None) -> Representation: ...
    def nucleic_acid(self, *, target: _Target, width: float | None = None, opacity: float = 1.0, color: _ColorLike | None = None) -> Representation: ...
    def bases(self, *, target: _Target, opacity: float = 1.0, color: _ColorLike | None = None) -> Representation: ...
    def base_pairs(self, *, target: _Target, opacity: float = 1.0, color: _ColorLike | None = None) -> Representation: ...
    def glycan(self, *, target: _Target, width: float | None = None, opacity: float = 1.0, color: _ColorLike | None = None) -> Representation: ...

class _Color:
    def element(self) -> ColorSpec: ...
    def chain(self) -> ColorSpec: ...
    def residue(self) -> ColorSpec: ...
    def secondary_structure(self) -> ColorSpec: ...
    def uniform(self, rgb: _Rgb) -> ColorSpec: ...
    def property(self, *, name: str, ramp: str, domain: tuple[float, float], units: str | None = None, missing: _Rgb = (128, 128, 128)) -> ColorSpec: ...

class _Profile:
    def interactive(self) -> RenderProfile: ...
    def publication(self) -> RenderProfile: ...
    def adaptive(self, target_fps: int) -> RenderProfile: ...

class _Visual:
    def scalar(self, value: float) -> ScalarExpr: ...
    def property(self, name: str) -> ScalarExpr: ...
    def parameter(self, default: float, *, name: str) -> ScalarParameter: ...
    def vector(self, value: tuple[float, float, float]) -> VectorExpr: ...
    def vector_property(self, name: str) -> VectorExpr: ...
    def vector_parameter(self, default: tuple[float, float, float], *, name: str) -> VectorParameter: ...
    def color_parameter(self, default: _Rgb, *, name: str) -> ColorParameter: ...
    def state(self, name: str) -> BoolExpr: ...
    def color(self, rgb: _Rgb) -> ColorExpr: ...
    def ramp(self, value: _ScalarLike, *, palette: str, domain: tuple[float, float], missing: _Rgb = (128, 128, 128)) -> ColorExpr: ...
    def where(self, condition: BoolExpr, yes: _ColorExprLike, no: _ColorExprLike) -> ColorExpr: ...
    def style(self, *, color: _ColorExprLike, opacity: _ScalarLike = 1.0, visible: _BoolLike = True) -> VisualStyle: ...

rep: _Rep
color: _Color
profile: _Profile
visual: _Visual
__version__: str
__all__ = [
    "__version__",
    "MolgfxError",
    "SpecError",
    "RevisionConflict",
    "Representation",
    "SceneSpec",
    "ScenePatch",
    "Scene",
    "SceneTransaction",
    "ColorSpec",
    "RenderProfile",
    "Camera",
    "color",
    "profile",
    "PickResult",
    "Image",
    "Renderer",
    "ScalarExpr",
    "ScalarParameter",
    "VectorExpr",
    "VectorParameter",
    "BoolExpr",
    "ColorExpr",
    "ColorParameter",
    "VisualStyle",
    "visual",
    "rep",
]
