//! Generated by `scripts/generate_bindings.py`; do not edit.

use super::dataset::PyChunkBounds;
use super::dataset::PyChunkDescriptor;
use super::dataset::PyChunkFootprint;
use super::dataset::PyChunkId;
use super::dataset::PyChunkSpan;
use super::dataset::PyDatasetCatalog;
use super::dataset::PyDatasetId;
use super::dataset::PyLocalRow;
use super::dataset::PyLogicalRow;
use super::dataset::PyPayloadKind;
use super::residency::PyDeviceLossReport;
use super::residency::PyResidencyBudget;
use super::residency::PyResidencyClass;
use super::residency::PyResidencyEviction;
use super::residency::PyResidencyFailure;
use super::residency::PyResidencyKey;
use super::residency::PyResidencyMachine;
use super::residency::PyResidencyOutput;
use super::residency::PyResidencyPhase;
use super::residency::PyResidencyRequest;
use super::residency::PyResidencySnapshot;
use super::residency::PyResidencyTicket;
use super::residency::PyResidencyUsage;
use super::residency::PyStaleCompletion;
use pyo3::prelude::*;

pub(super) fn register_dataset(module: &Bound<'_, PyModule>) -> PyResult<()> {
    module.add_class::<PyDatasetId>()?;
    module.add_class::<PyChunkId>()?;
    module.add_class::<PyLogicalRow>()?;
    module.add_class::<PyLocalRow>()?;
    module.add_class::<PyChunkFootprint>()?;
    module.add_class::<PyPayloadKind>()?;
    module.add_class::<PyChunkSpan>()?;
    module.add_class::<PyChunkBounds>()?;
    module.add_class::<PyChunkDescriptor>()?;
    module.add_class::<PyDatasetCatalog>()?;
    Ok(())
}

pub(super) fn register_residency(module: &Bound<'_, PyModule>) -> PyResult<()> {
    module.add_class::<PyResidencyBudget>()?;
    module.add_class::<PyResidencyUsage>()?;
    module.add_class::<PyResidencyClass>()?;
    module.add_class::<PyResidencyPhase>()?;
    module.add_class::<PyResidencyFailure>()?;
    module.add_class::<PyResidencyKey>()?;
    module.add_class::<PyResidencyTicket>()?;
    module.add_class::<PyResidencyRequest>()?;
    module.add_class::<PyResidencySnapshot>()?;
    module.add_class::<PyResidencyEviction>()?;
    module.add_class::<PyStaleCompletion>()?;
    module.add_class::<PyDeviceLossReport>()?;
    module.add_class::<PyResidencyOutput>()?;
    module.add_class::<PyResidencyMachine>()?;
    Ok(())
}
