[package]
name = "pdviewx-geometry"
description = "GPU geometry generation: impostor packing, cartoons, labels, bounding hierarchies."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]

[lints]
workspace = true
