//! The shared WGSL shader library and its build-time composition and
//! validation.

#![forbid(unsafe_code)]

mod sources;

pub use sources::{
    AMBIENT_OCCLUSION, AO_DENOISE, BLOOM, CULL, DEPTH_OF_FIELD, GEOMETRY_BOND, GEOMETRY_CARTOON,
    GEOMETRY_INTERACTION, GEOMETRY_LABEL, GEOMETRY_POINT, GEOMETRY_PRIMITIVE, GEOMETRY_SPHERE,
    GEOMETRY_SURFACE, LABEL_DECLUTTER, LIGHTING, MOTION_BLUR, OIT_COMPOSITE, OVERLAY,
    PARTICLE_ADVECTION, QUALITY_AO, SEGMENTATION, SHADOW, SURFACE_FIELD_COMPUTE,
    SURFACE_FIELD_ERODE, TEMPORAL_RESOLVE, TONEMAP, TRAJECTORY, VOLUME,
};
