// Builds the one MolGFX browser runtime: the wasm bindings, the notebook
// widget, the plain-page `mount()` entry and their stylesheet, into dist/.
// Every consumer (the Python wheel, the documentation site) copies dist/
// as-is, so nothing about the runtime is decided twice.
//
//   node scripts/build.mjs [--dev] [--no-wasm] [--out <dir>]...
//
// --dev      debug wasm (fast to build, large); the default is --release,
//            which wasm-pack also runs through wasm-opt.
// --no-wasm  reuse pkg/ from an earlier build; only the TypeScript is rebuilt.
// --out      also copy dist/ into <dir>; may be repeated.
import { build } from "esbuild";
import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { copyFileSync, cpSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const crate = dirname(root);
const pkg = join(root, "pkg");
const dist = join(root, "dist");

const args = process.argv.slice(2);
const flag = (name) => args.includes(name);
const outs = args.flatMap((arg, index) => (arg === "--out" ? [resolve(args[index + 1] ?? "")] : []));

if (!flag("--no-wasm")) {
  execFileSync(
    "wasm-pack",
    ["build", crate, flag("--dev") ? "--dev" : "--release", "--target", "web", "--out-dir", pkg, "--out-name", "molgfx_wasm", "--no-pack"],
    { stdio: "inherit" },
  );
}

const runtime = ["molgfx_wasm.js", "molgfx_wasm_bg.wasm"];
const missing = runtime.filter((name) => !existsSync(join(pkg, name)));
if (missing.length > 0) {
  throw new Error(`no wasm runtime in ${pkg} (missing ${missing.join(", ")}); build without --no-wasm`);
}

// Typecheck against the bindings just built, before anything is bundled.
execFileSync(process.execPath, [join(root, "node_modules", "typescript", "bin", "tsc"), "-p", join(root, "tsconfig.json")], { stdio: "inherit" });

rmSync(dist, { recursive: true, force: true });
mkdirSync(dist, { recursive: true });

await build({
  entryPoints: { widget: join(root, "src", "entry", "anywidget.ts"), mount: join(root, "src", "entry", "mount.ts") },
  outdir: dist,
  bundle: true,
  // The runtime glue stays a separate file: `mount.js` imports it beside
  // itself, and the widget receives it inline from the kernel.
  external: ["./molgfx_wasm.js"],
  format: "esm",
  platform: "browser",
  target: ["es2022"],
  minify: true,
  sourcemap: true,
  legalComments: "none",
  charset: "utf8",
  banner: { js: "// Generated by crates/molgfx-wasm/js/scripts/build.mjs. Do not edit." },
});

copyFileSync(join(root, "src", "widget.css"), join(dist, "widget.css"));
for (const name of runtime) copyFileSync(join(pkg, name), join(dist, name));

// The one place the runtime's content key is computed; the Python loader
// recomputes it to verify what it ships.
const glue = readFileSync(join(pkg, "molgfx_wasm.js"));
const wasm = readFileSync(join(pkg, "molgfx_wasm_bg.wasm"));
const contentKey = createHash("sha256").update(glue).update(Buffer.from([0])).update(wasm).digest("hex").slice(0, 16);
writeFileSync(
  join(dist, "runtime-manifest.json"),
  JSON.stringify({ available: true, glue: runtime[0], wasm: runtime[1], content_key: contentKey }) + "\n",
);

for (const out of outs) {
  rmSync(out, { recursive: true, force: true });
  cpSync(dist, out, { recursive: true });
}

console.log(`molgfx-wasm: built ${dist} (${(wasm.length / 1e6).toFixed(1)} MB wasm, key ${contentKey})`);
