//! Generated by `scripts/generate_bindings.py`; do not edit.

use pyo3::prelude::*;

pub(crate) fn register(module: &Bound<'_, PyModule>) -> PyResult<()> {
    crate::error::register(module)?;
    crate::math::register(module)?;
    crate::memory::register(module)?;
    crate::controls::register(module)?;
    crate::core::register(module)?;
    crate::annotations::register(module)?;
    crate::authoring::register(module)?;
    crate::overlay_authoring::register(module)?;
    crate::pending_surface::register(module)?;
    crate::validation_markers::register(module)?;
    crate::semantic::register(module)?;
    crate::trajectory::register(module)?;
    crate::topology::register(module)?;
    crate::timeline::register(module)?;
    crate::values::register(module)?;
    crate::visual::register(module)?;
    crate::render::register(module)
}
