[package]
name = "molgfx-wasm"
description = "Thin browser bindings for molgfx over WebGPU."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
js-sys.workspace = true
molgfx.workspace = true
molframe = { workspace = true, features = ["mmcif", "bcif", "pdb", "chem", "spatial"] }
wasm-bindgen.workspace = true
wasm-bindgen-futures.workspace = true
web-sys.workspace = true

[lints]
workspace = true
