[package]
name = "molgfx-recipes"
description = "Optional molecular visualization recipes built as consumers of the generic molgfx engine."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
thiserror.workspace = true
molgfx-core.workspace = true
molgfx-math.workspace = true
molgfx-semantic.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
pdbiox = { workspace = true, features = ["mmcif"] }

[lints]
workspace = true
