//! The shared WGSL shader library and its build-time composition and
//! validation.

#![forbid(unsafe_code)]

mod sources;

pub use sources::{
    AMBIENT_OCCLUSION, AO_DENOISE, ATTRIBUTE_TIMELINE, BLOOM, CULL, DEPTH_OF_FIELD,
    GENERIC_INSTANCE, GENERIC_INSTANCE_CULL, GENERIC_POINT, GENERIC_POINT_CULL, GEOMETRY_BOND,
    GEOMETRY_CARTOON, GEOMETRY_INTERACTION, GEOMETRY_LABEL, GEOMETRY_LIGAND_POSE, GEOMETRY_POINT,
    GEOMETRY_PRIMITIVE, GEOMETRY_SPHERE, GEOMETRY_SURFACE, INSTANCE_TIMELINE, LABEL_DECLUTTER,
    LIGAND_POSE_SHADOW, LIGHTING, MOTION_BLUR, OCCUPANCY, OIT_COMPOSITE, OVERLAY, PAGED_BOND,
    PAGED_CHUNK, PARTICLE_ADVECTION, POINT_TIMELINE, QUALITY_AO, QUALITY_AO_RAY_QUERY,
    RELATION_CULL, RELATION_RESOLVE, SEGMENTATION, SHADOW, SHADOW_RIBBON, SURFACE_COMPONENT_FILTER,
    SURFACE_FIELD_COMPUTE, SURFACE_FIELD_ERODE, SURFACE_FIELD_NORMAL, TEMPORAL_RESOLVE, TONEMAP,
    TRAJECTORY, VISUAL_PROGRAM, VOLUME,
};
