"""Declarative, GPU-native molecular rendering."""

from importlib import import_module
from typing import TYPE_CHECKING

from molframe import sel as sel

from ._engine import (
    Anchor,
    AnnotationId,
    ArcballController,
    AssemblyCopy,
    BoolExpr,
    Camera,
    CameraPath,
    ColorExpr,
    ColorParameter,
    Command,
    CommandError,
    CommandResult,
    DataSource,
    DifferenceStyle,
    EllipsoidId,
    FlyController,
    HdrImage,
    Image,
    Interaction,
    InteractionId,
    Label,
    Measurement,
    MeasurementId,
    MolgfxError,
    OrbitController,
    PickResult,
    PocketStyle,
    Renderer,
    RenderProfile,
    Representation,
    RepresentationId,
    RevisionConflict,
    ScalarExpr,
    ScalarParameter,
    ScalarProperty,
    Scene,
    ScenePatch,
    SceneSpec,
    SceneTransaction,
    Session,
    SpecError,
    StructureId,
    Trajectory,
    TrajectoryId,
    VectorExpr,
    VectorParameter,
    VisualStyle,
    Volume,
    VolumeId,
    __version__,
    annotation,
    color,
    data,
    density,
    ellipsoid,
    interaction,
    measurement,
    profile,
    rep,
    system_info,
    trajectory,
    visual,
    vocabulary,
)

if TYPE_CHECKING:
    from .viewer import Viewer


def __getattr__(name: str) -> object:
    """Load the notebook adapter only when it is explicitly requested."""
    if name == "Viewer":
        viewer: object = import_module(".viewer", __name__).Viewer
        globals()[name] = viewer
        return viewer
    message = f"module {__name__!r} has no attribute {name!r}"
    raise AttributeError(message)


__all__ = [
    "Anchor",
    "AnnotationId",
    "ArcballController",
    "AssemblyCopy",
    "BoolExpr",
    "Camera",
    "CameraPath",
    "ColorExpr",
    "ColorParameter",
    "Command",
    "CommandError",
    "CommandResult",
    "DataSource",
    "DifferenceStyle",
    "EllipsoidId",
    "FlyController",
    "HdrImage",
    "Image",
    "Interaction",
    "InteractionId",
    "Label",
    "Measurement",
    "MeasurementId",
    "MolgfxError",
    "OrbitController",
    "PickResult",
    "PocketStyle",
    "RenderProfile",
    "Renderer",
    "Representation",
    "RepresentationId",
    "RevisionConflict",
    "ScalarExpr",
    "ScalarParameter",
    "ScalarProperty",
    "Scene",
    "ScenePatch",
    "SceneSpec",
    "SceneTransaction",
    "Session",
    "SpecError",
    "StructureId",
    "Trajectory",
    "TrajectoryId",
    "VectorExpr",
    "VectorParameter",
    "Viewer",
    "VisualStyle",
    "Volume",
    "VolumeId",
    "__version__",
    "annotation",
    "color",
    "data",
    "density",
    "ellipsoid",
    "interaction",
    "measurement",
    "profile",
    "rep",
    "sel",
    "system_info",
    "trajectory",
    "visual",
    "vocabulary",
]
