from typing import Literal, Sequence
import numpy as np
from numpy.typing import NDArray

class Vec3:
    def __init__(self, x: float, y: float, z: float) -> None: ...
    x: float
    y: float
    z: float
    ZERO: Vec3
    X: Vec3
    Y: Vec3
    Z: Vec3
    def to_tuple(self) -> tuple[float, float, float]: ...
    def __repr__(self) -> str: ...

class Quat:
    def __init__(self, x: float, y: float, z: float, w: float) -> None: ...
    @staticmethod
    def identity() -> Quat: ...
    x: float
    y: float
    z: float
    w: float

class Mat4:
    def __init__(self, values: Sequence[float]) -> None: ...
    @staticmethod
    def identity() -> Mat4: ...
    def to_list(self) -> list[float]: ...
    def __repr__(self) -> str: ...

class Rgba8:
    def __init__(self, r: int, g: int, b: int, a: int) -> None: ...
    @staticmethod
    def opaque(r: int, g: int, b: int) -> Rgba8: ...
    WHITE: Rgba8
    r: int
    g: int
    b: int
    a: int
    def to_f32(self) -> tuple[float, float, float, float]: ...

class ScalarFieldSemantics:
    @staticmethod
    def uncalibrated_rank() -> ScalarFieldSemantics: ...
    @staticmethod
    def quantity(name: str, units: str, provenance: str) -> ScalarFieldSemantics: ...
    kind: str
class ScalarRamp:
    def __init__(self, values: tuple[float, float, float], colors: tuple[Rgba8, Rgba8, Rgba8]) -> None: ...
    @staticmethod
    def diverging(extent: float) -> ScalarRamp: ...
    @staticmethod
    def sequential(domain: tuple[float, float]) -> ScalarRamp: ...
    values: tuple[float, float, float]
    colors: tuple[Rgba8, Rgba8, Rgba8]
    def sample(self, value: float, missing: Rgba8) -> Rgba8: ...
class ScalarContours:
    def __init__(self, interval: float, width_pixels: float) -> None: ...
    interval: float
    width_pixels: float
class SurfaceScalarOverlay:
    def __init__(self, field: VolumeHandle, ramp: ScalarRamp) -> None: ...
    field: VolumeHandle
    ramp: ScalarRamp
    def with_contours(self, contours: ScalarContours) -> SurfaceScalarOverlay: ...
class ClipCap: ...
class ClipPlane:
    @staticmethod
    def from_point_normal(point: Vec3, normal: Vec3) -> ClipPlane: ...
    normal: Vec3
    offset: float
    def reversed(self) -> ClipPlane: ...
    def signed_distance(self, point: Vec3) -> float: ...
class ClipSet:
    def __init__(self, planes: Sequence[ClipPlane]) -> None: ...
    @staticmethod
    def slab(center: Vec3, normal: Vec3, thickness: float) -> ClipSet: ...
    def with_cap(self, cap: ClipCap) -> ClipSet: ...
    cap: ClipCap
    plane_count: int
    def contains(self, point: Vec3) -> bool: ...
class SegmentStyle:
    def __init__(self, label: int, color: Rgba8, opacity: float) -> None: ...
    label: int
    color: Rgba8
    opacity: float
class SegmentStyleTable:
    def __init__(self, styles: Sequence[SegmentStyle]) -> None: ...
    @staticmethod
    def default() -> SegmentStyleTable: ...
    def style_for(self, label: int) -> SegmentStyle | None: ...
    len: int
class SegmentationStyle:
    def __init__(self, styles: SegmentStyleTable | None = ..., opacity_scale: float = ..., step_scale: float = ...) -> None: ...
    @staticmethod
    def default() -> SegmentationStyle: ...
    styles: SegmentStyleTable
    opacity_scale: float
    step_scale: float
class VolumeStyle:
    @staticmethod
    def direct() -> VolumeStyle: ...
    @staticmethod
    def isosurface() -> VolumeStyle: ...
    @staticmethod
    def medium() -> VolumeStyle: ...
    @staticmethod
    def liquid_surface() -> VolumeStyle: ...
    @staticmethod
    def slice(plane: ClipPlane) -> VolumeStyle: ...
    def region(self, minimum: tuple[int, int, int], maximum: tuple[int, int, int], dimensions: tuple[int, int, int]) -> VolumeStyle: ...
    def sampling(self, opacity_scale: float, step_scale: float) -> VolumeStyle: ...
class TubeRadiusMapping:
    @staticmethod
    def constant() -> TubeRadiusMapping: ...
    @staticmethod
    def b_factor(domain: tuple[float, float], radii: tuple[float, float]) -> TubeRadiusMapping: ...
    def radius(self, value: float, fallback: float) -> float: ...
    def value(self, radius: float) -> float | None: ...
class CrystalCell:
    def __init__(self, lengths: tuple[float, float, float], angles_degrees: tuple[float, float, float]) -> None: ...
    def with_origin(self, origin: Vec3) -> CrystalCell: ...
    lengths: tuple[float, float, float]
    angles_degrees: tuple[float, float, float]
    origin: Vec3
class SymmetryInstance:
    def __init__(self, id: int, transform: Mat4) -> None: ...
    id: int
    transform: Mat4
class TrajectoryFrame:
    def __init__(self, index: int, time_seconds: float, positions: Sequence[Vec3], provenance: str) -> None: ...
    index: int
    time_seconds: float
    positions: list[Vec3]
    provenance: str
    def aabb(self) -> Aabb: ...
class TrajectorySegment:
    def __init__(self, start: TrajectoryFrame, end: TrajectoryFrame, sample_seconds: float) -> None: ...
    def set_sample_time(self, sample_seconds: float) -> None: ...
    start: TrajectoryFrame
    end: TrajectoryFrame
    sample_seconds: float
    interpolation: float
    atom_count: int
    def union_aabb(self) -> Aabb: ...

class Aabb:
    def __init__(self, min: Vec3, max: Vec3) -> None: ...
    EMPTY: Aabb
    min: Vec3
    max: Vec3
    def is_empty(self) -> bool: ...
    def center(self) -> Vec3: ...
    def bounding_sphere(self) -> BoundingSphere: ...

class BoundingSphere:
    def __init__(self, center: Vec3, radius: float) -> None: ...
    center: Vec3
    radius: float

class Projection:
    @staticmethod
    def perspective(fov_y: float, aspect: float, near: float = ..., far: float = ...) -> Projection: ...
    @staticmethod
    def orthographic(height: float, aspect: float, near: float = ..., far: float = ...) -> Projection: ...
    aspect: float
    kind: Literal["perspective", "orthographic"]
    def __repr__(self) -> str: ...

class Camera:
    def __init__(self, eye: Vec3, target: Vec3, up: Vec3, projection: Projection) -> None: ...
    @staticmethod
    def framing(bound: BoundingSphere, aspect: float) -> Camera: ...
    @staticmethod
    def framing_aabb(bound: Aabb, aspect: float) -> Camera: ...
    @staticmethod
    def look_at(eye: Vec3, target: Vec3, up: Vec3) -> Mat4: ...
    eye: Vec3
    target: Vec3
    up: Vec3
    projection: Projection
    focus_distance: float
    def view_proj(self) -> Mat4: ...

class PropertyComparison:
    Less: PropertyComparison
    LessOrEqual: PropertyComparison
    Equal: PropertyComparison
    GreaterOrEqual: PropertyComparison
    Greater: PropertyComparison
class SecondaryStructure:
    Coil: SecondaryStructure
    Helix: SecondaryStructure
    Strand: SecondaryStructure
    Turn: SecondaryStructure
class Select:
    @staticmethod
    def parse(source: str) -> Select: ...
    @staticmethod
    def all() -> Select: ...
    @staticmethod
    def none() -> Select: ...
    @staticmethod
    def polymer() -> Select: ...
    @staticmethod
    def protein() -> Select: ...
    @staticmethod
    def nucleic() -> Select: ...
    @staticmethod
    def ligands() -> Select: ...
    @staticmethod
    def water() -> Select: ...
    @staticmethod
    def branched() -> Select: ...
    @staticmethod
    def chain(label: str) -> Select: ...
    @staticmethod
    def residue_name(name: str) -> Select: ...
    @staticmethod
    def atom_name(name: str) -> Select: ...
    @staticmethod
    def residue(number: int) -> Select: ...
    @staticmethod
    def element(symbol: str) -> Select: ...
    @staticmethod
    def secondary(value: SecondaryStructure) -> Select: ...
    @staticmethod
    def helix() -> Select: ...
    @staticmethod
    def sheet() -> Select: ...
    @staticmethod
    def coil() -> Select: ...
    @staticmethod
    def hydrogen() -> Select: ...
    @staticmethod
    def heavy() -> Select: ...
    @staticmethod
    def backbone() -> Select: ...
    @staticmethod
    def terminus() -> Select: ...
    @staticmethod
    def b_factor(comparison: PropertyComparison, threshold: float) -> Select: ...
    @staticmethod
    def occupancy(comparison: PropertyComparison, threshold: float) -> Select: ...
    @staticmethod
    def within(distance: float, reference: Select) -> Select: ...
    @staticmethod
    def residues_within(distance: float, reference: Select) -> Select: ...
    @staticmethod
    def beyond(distance: float, reference: Select) -> Select: ...
    @staticmethod
    def in_sphere(center: Vec3, radius: float) -> Select: ...
    @staticmethod
    def in_box(min: Vec3, max: Vec3) -> Select: ...
    def and_(self, other: Select) -> Select: ...
    def or_(self, other: Select) -> Select: ...
    def negate(self) -> Select: ...
    def __repr__(self) -> str: ...

def select(source: str) -> Select: ...

class RepresentationKind:
    Spacefill: RepresentationKind
    BallAndStick: RepresentationKind
    Licorice: RepresentationKind
    Lines: RepresentationKind
    Cartoon: RepresentationKind
    Trace: RepresentationKind
    Tube: RepresentationKind
    Surface: RepresentationKind
    Volume: RepresentationKind
    Segmentation: RepresentationKind
    Beads: RepresentationKind
    Rocket: RepresentationKind
    Twister: RepresentationKind
    PaperChain: RepresentationKind
    Points: RepresentationKind
class Representation:
    @staticmethod
    def spacefill() -> Representation: ...
    @staticmethod
    def ball_and_stick() -> Representation: ...
    @staticmethod
    def licorice() -> Representation: ...
    @staticmethod
    def lines() -> Representation: ...
    @staticmethod
    def cartoon() -> Representation: ...
    @staticmethod
    def trace() -> Representation: ...
    @staticmethod
    def tube() -> Representation: ...
    @staticmethod
    def surface() -> Representation: ...
    @staticmethod
    def volume() -> Representation: ...
    @staticmethod
    def segmentation() -> Representation: ...
    @staticmethod
    def beads() -> Representation: ...
    @staticmethod
    def rocket() -> Representation: ...
    @staticmethod
    def twister() -> Representation: ...
    @staticmethod
    def paper_chain() -> Representation: ...
    @staticmethod
    def points() -> Representation: ...
    def color(self, color: ColorScheme) -> Representation: ...
    def material(self, material: Material) -> Representation: ...
    def clipping(self, clipping: ClipSet) -> Representation: ...
    def radius_scale(self, scale: float) -> Representation: ...
    def bond_radius(self, radius: float) -> Representation: ...
    def isolevel(self, level: float) -> Representation: ...
    def surface_presentation(self, kind: SurfaceKind, style: SurfaceStyle) -> Representation: ...
    def volume_style(self, style: VolumeStyle) -> Representation: ...
    def segmentation_style(self, style: SegmentationStyle) -> Representation: ...
    def surface_scalar(self, overlay: SurfaceScalarOverlay) -> Representation: ...
    kind: RepresentationKind
    def __repr__(self) -> str: ...

class RepresentationPreset:
    @staticmethod
    def cpk() -> RepresentationPreset: ...
    @staticmethod
    def licorice() -> RepresentationPreset: ...
    @staticmethod
    def paper_chain() -> RepresentationPreset: ...
    @staticmethod
    def dotted_solvent() -> RepresentationPreset: ...
    @staticmethod
    def signed_isosurface(negative_level: float, positive_level: float, negative_color: Rgba8, positive_color: Rgba8) -> RepresentationPreset: ...

class MaterialModel:
    @staticmethod
    def molecular() -> MaterialModel: ...
    @staticmethod
    def principled(metallic: float) -> MaterialModel: ...
    @staticmethod
    def anisotropic_ribbon(strength: float) -> MaterialModel: ...
    @staticmethod
    def diffusion(strength: float) -> MaterialModel: ...
    def __repr__(self) -> str: ...
class Material:
    @staticmethod
    def default() -> Material: ...
    @staticmethod
    def principled(metallic: float) -> Material: ...
    @staticmethod
    def anisotropic_ribbon(strength: float) -> Material: ...
    @staticmethod
    def diffusion(strength: float) -> Material: ...
    opacity: float
    roughness: float
    specular: float
    model: MaterialModel
class DensityVolume:
    def __init__(self, dimensions: tuple[int, int, int], values: Sequence[float], voxel_to_world: Mat4 | None = ...) -> None: ...
    dimensions: tuple[int, int, int]
    range: tuple[float, float]
    values: list[float]
    voxel_to_world: Mat4
class SegmentedVolume:
    def __init__(self, dimensions: tuple[int, int, int], labels: Sequence[int], voxel_to_world: Mat4 | None = ...) -> None: ...
    dimensions: tuple[int, int, int]
    labels: list[int]
    voxel_to_world: Mat4

class StructureHandle:
    row: int
    generation: int
class SelectionHandle(StructureHandle): ...
class Selection(SelectionHandle): ...
class VolumeHandle(StructureHandle): ...
class SegmentationHandle(StructureHandle): ...
class RepresentationHandle(StructureHandle): ...

class AtomPropertyHandle(StructureHandle): ...
class MeshHandle(StructureHandle): ...
class MeshInstanceHandle(StructureHandle): ...
class OverlayHandle(StructureHandle): ...
class EnsembleHandle: ...
class InteractionHandle: ...
class GuideHandle: ...
class AnnotationHandle: ...
class MeasurementHandle: ...
class EntityKind: ...
class EntityRef:
    def __init__(self, structure: StructureHandle, kind: EntityKind, index: int) -> None: ...
    structure: StructureHandle
    kind: EntityKind
    index: int
class VolumeSegmentRef:
    def __init__(self, volume: SegmentationHandle, label: int) -> None: ...
    volume: SegmentationHandle
    label: int

class Provenance:
    entity: EntityRef
    entry_id: str | None
    entry_title: str | None
    method: str | None
    resolution: float | None
    detail_kind: str

Selection = SelectionHandle

class ColorScheme:
    @staticmethod
    def by_element() -> ColorScheme: ...
    @staticmethod
    def by_chain() -> ColorScheme: ...
    @staticmethod
    def by_residue() -> ColorScheme: ...
    @staticmethod
    def by_secondary_structure() -> ColorScheme: ...
    @staticmethod
    def by_property(property: AtomPropertyHandle, ramp: ScalarRamp, missing: Rgba8) -> ColorScheme: ...
    @staticmethod
    def uniform(color: Rgba8) -> ColorScheme: ...
    kind: str
    property: AtomPropertyHandle | None
class SurfaceKind:
    VanDerWaals: SurfaceKind
    SolventAccessible: SurfaceKind
    SolventExcluded: SurfaceKind
    Gaussian: SurfaceKind
class SurfaceStyle:
    Solid: SurfaceStyle
    Contour: SurfaceStyle
    Dots: SurfaceStyle
    FilledContour: SurfaceStyle

class AnnotationAnchor:
    @staticmethod
    def world(position: Vec3) -> AnnotationAnchor: ...
    @staticmethod
    def entity(position: Vec3, entity: EntityRef) -> AnnotationAnchor: ...
    position: Vec3
    source_entity: EntityRef | None
class MarkerShape:
    Circle: MarkerShape
    Diamond: MarkerShape
    Crosshair: MarkerShape
class MarkerStyle:
    def __init__(self, color: Rgba8 | None = ..., radius_pixels: float = ..., shape: MarkerShape | None = ...) -> None: ...
    color: Rgba8
    radius_pixels: float
    shape: MarkerShape
class AnnotationKind:
    Note: AnnotationKind
    Marker: AnnotationKind
    Region: AnnotationKind
    Hypothesis: AnnotationKind
class Annotation:
    @staticmethod
    def note(owner: StructureHandle, anchor: AnnotationAnchor, text: str) -> Annotation: ...
    @staticmethod
    def hypothesis(owner: StructureHandle, anchor: AnnotationAnchor, text: str) -> Annotation: ...
    @staticmethod
    def marker(owner: StructureHandle, anchor: AnnotationAnchor, style: MarkerStyle) -> Annotation: ...
    @staticmethod
    def region(owner: StructureHandle, selection: SelectionHandle, label: str) -> Annotation: ...
    def with_priority(self, priority: int) -> Annotation: ...
    owner: StructureHandle
    kind: AnnotationKind
    anchor: AnnotationAnchor | None
    region_selection: SelectionHandle | None
    text: str
    marker_style: MarkerStyle
    priority: int
    visible: bool
class MeasurementKind:
    Distance: MeasurementKind
    Angle: MeasurementKind
    Dihedral: MeasurementKind
class Measurement:
    @staticmethod
    def distance(owner: StructureHandle, anchors: Sequence[AnnotationAnchor], value: float, provenance: str) -> Measurement: ...
    @staticmethod
    def angle(owner: StructureHandle, anchors: Sequence[AnnotationAnchor], value: float, provenance: str) -> Measurement: ...
    @staticmethod
    def dihedral(owner: StructureHandle, anchors: Sequence[AnnotationAnchor], value: float, provenance: str) -> Measurement: ...
    owner: StructureHandle
    kind: MeasurementKind
    anchors: list[AnnotationAnchor]
    value: float
    label: str
    provenance: str
    def with_priority(self, priority: int) -> Measurement: ...
    priority: int
    visible: bool

class InteractionKind:
    HydrogenBond: InteractionKind
    SaltBridge: InteractionKind
    PiStacking: InteractionKind
    Hydrophobic: InteractionKind
    MetalCoordination: InteractionKind
class InteractionDirection:
    Undirected: InteractionDirection
    Forward: InteractionDirection
    Reverse: InteractionDirection
class InteractionPattern:
    Solid: InteractionPattern
    Dashes: InteractionPattern
    Dots: InteractionPattern
    Spring: InteractionPattern
class InteractionGeometry:
    def __init__(self, distance_angstrom: float, angle_degrees: float | None = ...) -> None: ...
    distance_angstrom: float
    angle_degrees: float | None
class InteractionStyle:
    color: Rgba8
    pattern: InteractionPattern
    width_pixels: float
    opacity: float
    period_pixels: float
    duty_cycle: float
class InteractionAnchor:
    @staticmethod
    def world(position: Vec3) -> InteractionAnchor: ...
    @staticmethod
    def entity(position: Vec3, entity: EntityRef) -> InteractionAnchor: ...
    position: Vec3
    source_entity: EntityRef | None
class InteractionEdge:
    def __init__(self, owner: StructureHandle, start: InteractionAnchor, end: InteractionAnchor, kind: InteractionKind, geometry: InteractionGeometry, provenance: str) -> None: ...
    def with_direction(self, direction: InteractionDirection) -> InteractionEdge: ...
    def with_occupancy(self, value: float) -> InteractionEdge: ...
    def with_normalized_strength(self, value: float) -> InteractionEdge: ...
    def with_phase_speed(self, value: float) -> InteractionEdge: ...
    def with_persistence(self, age: int, half_life: float) -> InteractionEdge: ...
    owner: StructureHandle
    start: InteractionAnchor
    end: InteractionAnchor
    kind: InteractionKind
    direction: InteractionDirection
    geometry: InteractionGeometry
    occupancy: float | None
    normalized_strength: float | None
    provenance: str
    def resolved_style(self) -> InteractionStyle: ...

class DistanceBands:
    def __init__(self, near: float, mid: float) -> None: ...
    @staticmethod
    def default() -> DistanceBands: ...
    near: float
    mid: float
    def classify(self, distance: float) -> FocusBand: ...
class FocusStyle:
    def __init__(self, bands: DistanceBands | None = ..., pocket_opacity: float = ..., context_opacity: float = ..., pocket_presentation: SurfaceStyle | None = ..., surface_extent: FocusSurfaceExtent | None = ..., pocket_color: Rgba8 | None = ..., context_geometry: FocusContext | None = ..., context_color: Rgba8 | None = ..., solvent_opacity: float = ..., solvent_color: Rgba8 | None = ...) -> None: ...
    @staticmethod
    def default() -> FocusStyle: ...
    bands: DistanceBands
class AtomCorrespondence:
    def __init__(self, left: int, right: int) -> None: ...
    left: int
    right: int
class DifferenceStyle:
    def __init__(self, tolerance_angstrom: float = ..., context_opacity: float = ..., representation: RepresentationKind | None = ...) -> None: ...
    @staticmethod
    def default() -> DifferenceStyle: ...
    tolerance_angstrom: float
    context_opacity: float
    representation: RepresentationKind
class DifferenceView:
    properties: tuple[AtomPropertyHandle, AtomPropertyHandle]
    selections: tuple[SelectionHandle, SelectionHandle]
    representations: tuple[RepresentationHandle, RepresentationHandle]
    maximum_displacement: float
class Ensemble:
    def __init__(self, members: Sequence[StructureHandle], weights: Sequence[float], provenance: str) -> None: ...
    members: list[StructureHandle]
    weights: list[float]
    provenance: str
    dominant: int
class EnsembleStyle:
    def __init__(self, representation: RepresentationKind | None = ..., alternate_opacity: float = ..., minimum_opacity: float = ...) -> None: ...
    @staticmethod
    def default() -> EnsembleStyle: ...
class EnsembleView:
    ensemble: EnsembleHandle
    selections: list[SelectionHandle]
    representations: list[RepresentationHandle]
    dominant: int
class ProbabilityCloudView:
    ensemble: EnsembleHandle
    volume: VolumeHandle
    representation: RepresentationHandle
class LodLevel:
    Atom: LodLevel
    Residue: LodLevel
    SecondaryStructure: LodLevel
    Domain: LodLevel
class LodPolicy:
    def __init__(self, atom_pixels: float = ..., residue_pixels: float = ..., secondary_pixels: float = ..., hysteresis: float = ...) -> None: ...
    @staticmethod
    def default() -> LodPolicy: ...
    def select(self, error_pixels: float, importance: float, previous: LodLevel) -> LodLevel: ...
class StreamingBudget:
    def __init__(self, max_resident_bytes: int = ..., max_requests_per_frame: int = ...) -> None: ...
    @staticmethod
    def default() -> StreamingBudget: ...
    max_resident_bytes: int
    max_requests_per_frame: int
class ChunkKey:
    def __init__(self, structure: StructureHandle, level: LodLevel, index: int) -> None: ...
    structure: StructureHandle
    level: LodLevel
    index: int
class ChunkRequest:
    def __init__(self, key: ChunkKey, priority: float, bytes: int) -> None: ...
    key: ChunkKey
    priority: float
    bytes: int
class StreamPlan:
    retain: list[ChunkRequest]
    evict: list[ChunkKey]
    resident_bytes: int
class StreamPlanner:
    def __init__(self, budget: StreamingBudget | None = ...) -> None: ...
    budget: StreamingBudget
    def plan(self, requests: Sequence[ChunkRequest]) -> StreamPlan: ...

class Scene:
    def __init__(self) -> None: ...
    @staticmethod
    def from_structure(structure: object) -> Scene: ...
    def add_structure(self, structure: object) -> StructureHandle: ...
    def select(self, query: Select) -> SelectionHandle: ...
    def select_str(self, source: str) -> SelectionHandle: ...
    def represent(self, target: Select | SelectionHandle | str | VolumeHandle | SegmentationHandle, representation: Representation) -> RepresentationHandle: ...
    def represent_preset(self, selection: Select | SelectionHandle | str, preset: RepresentationPreset) -> list[RepresentationHandle]: ...
    def add_volume(self, volume: DensityVolume) -> VolumeHandle: ...
    def add_segmented_volume(self, volume: SegmentedVolume) -> SegmentationHandle: ...
    def representation_kind(self, representation: RepresentationHandle) -> RepresentationKind | None: ...
    def set_trajectory_segment(self, structure: StructureHandle, segment: TrajectorySegment) -> None: ...
    def set_trajectory_time(self, structure: StructureHandle, sample_seconds: float) -> None: ...
    def clear_trajectory(self, structure: StructureHandle) -> bool: ...
    def provenance(self, entity: EntityRef) -> Provenance | None: ...
    def focus(self, selection: Select | SelectionHandle | str) -> FocusView: ...
    def focus_with(self, selection: SelectionHandle, style: FocusStyle) -> FocusView: ...
    def render_difference(self, structures: tuple[StructureHandle, StructureHandle], correspondence: Sequence[AtomCorrespondence], provenance: str, style: DifferenceStyle | None = ...) -> DifferenceView: ...
    def add_ensemble(self, ensemble: Ensemble) -> EnsembleHandle: ...
    def overlay_ensemble(self, ensemble: EnsembleHandle, style: EnsembleStyle | None = ...) -> EnsembleView: ...
    def probability_cloud(self, ensemble: EnsembleHandle, volume: VolumeHandle) -> ProbabilityCloudView: ...
    def add_annotation(self, annotation: Annotation) -> AnnotationHandle: ...
    def add_measurement(self, measurement: Measurement) -> MeasurementHandle: ...
    def annotation(self, handle: AnnotationHandle) -> Annotation | None: ...
    def measurement(self, handle: MeasurementHandle) -> Measurement | None: ...
    def add_interaction(self, interaction: InteractionEdge) -> InteractionHandle: ...
    def interaction(self, handle: InteractionHandle) -> InteractionEdge | None: ...
    def hide(self, representation: RepresentationHandle) -> None: ...
    def show(self, representation: RepresentationHandle) -> None: ...
    def remove_representation(self, representation: RepresentationHandle) -> None: ...
    representation_count: int
    structure_count: int
    interaction_count: int
    representation_revision: int
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

class FocusBand:
    Near: FocusBand
    Mid: FocusBand
    Far: FocusBand
class FocusContext:
    Cartoon: FocusContext
    Trace: FocusContext
    Tube: FocusContext
class FocusSurfaceExtent:
    Pocket: FocusSurfaceExtent
    Structure: FocusSurfaceExtent
class FocusView:
    focus: SelectionHandle
    near: SelectionHandle
    pocket: SelectionHandle
    mid: SelectionHandle
    context: SelectionHandle
    solvent: SelectionHandle
    focus_representation: RepresentationHandle
    near_representation: RepresentationHandle
    mid_representation: RepresentationHandle
    pocket_representation: RepresentationHandle
    context_representation: RepresentationHandle
    solvent_representation: RepresentationHandle

class RenderMode:
    Realtime: RenderMode
    Quality: RenderMode
class FrameOutcome:
    Presented: FrameOutcome
    Skipped: FrameOutcome
class ToneMapping:
    AcesFitted: ToneMapping
    Reinhard: ToneMapping
class DisplayGamut:
    Srgb: DisplayGamut
    DisplayP3: DisplayGamut
    Rec2020: DisplayGamut
class TransferFunction:
    Srgb: TransferFunction
    Linear: TransferFunction
    Pq: TransferFunction
    Hlg: TransferFunction
class FocusTarget:
    @staticmethod
    def camera_target() -> FocusTarget: ...
    @staticmethod
    def distance(value: float) -> FocusTarget: ...
    @staticmethod
    def world_point(value: Vec3) -> FocusTarget: ...
    @staticmethod
    def selection(value: SelectionHandle) -> FocusTarget: ...
    kind: str
class BackdropStyle:
    def __init__(self, top: Rgba8 | None = ..., bottom: Rgba8 | None = ..., glow_color: Rgba8 | None = ..., glow_strength: float = ...) -> None: ...
    @staticmethod
    def compositing() -> BackdropStyle: ...
    @staticmethod
    def transparent() -> BackdropStyle: ...
    @staticmethod
    def studio() -> BackdropStyle: ...
    top: Rgba8
    bottom: Rgba8
    glow_color: Rgba8
    glow_strength: float
class BloomStyle:
    def __init__(self, threshold: float = ..., intensity: float = ..., radius: float = ...) -> None: ...
    @staticmethod
    def cinematic() -> BloomStyle: ...
    threshold: float
    intensity: float
    radius: float
class DisplayTransform:
    def __init__(self, exposure_ev: float = ..., contrast: float = ..., saturation: float = ..., vignette_strength: float = ..., tone_mapping: ToneMapping | None = ..., gamut: DisplayGamut | None = ..., transfer: TransferFunction | None = ..., peak_luminance_nits: float = ...) -> None: ...
    @staticmethod
    def cinematic() -> DisplayTransform: ...
    exposure_ev: float
    contrast: float
    saturation: float
    vignette_strength: float
    tone_mapping: ToneMapping
    gamut: DisplayGamut
    transfer: TransferFunction
    peak_luminance_nits: float
class LightingEnvironment:
    @staticmethod
    def neutral() -> LightingEnvironment: ...
    @staticmethod
    def documentary() -> LightingEnvironment: ...
    zenith: Rgba8
    horizon: Rgba8
    ground: Rgba8
    key_direction: Vec3
    fill_direction: Vec3
class IllustrationStyle:
    def __init__(self, silhouette_strength: float = ..., cavity_strength: float = ..., depth_cue_strength: float = ...) -> None: ...
    @staticmethod
    def publication() -> IllustrationStyle: ...
    silhouette_strength: float
    cavity_strength: float
    depth_cue_strength: float
class DepthOfField:
    def __init__(self, focal_length_mm: float = ..., f_number: float = ..., sensor_width_mm: float = ..., max_blur_pixels: float = ..., blade_count: int = ..., focus: FocusTarget | None = ...) -> None: ...
    @staticmethod
    def cinematic() -> DepthOfField: ...
    focal_length_mm: float
    f_number: float
    sensor_width_mm: float
    max_blur_pixels: float
    blade_count: int
    focus: FocusTarget
class MotionBlur:
    def __init__(self, shutter: float = ..., max_blur_pixels: float = ...) -> None: ...
    @staticmethod
    def cinematic() -> MotionBlur: ...
    shutter: float
    max_blur_pixels: float
class PresentationEffect:
    @staticmethod
    def illustration(style: IllustrationStyle) -> PresentationEffect: ...
    @staticmethod
    def depth_of_field(settings: DepthOfField) -> PresentationEffect: ...
    @staticmethod
    def motion_blur(settings: MotionBlur) -> PresentationEffect: ...
    @staticmethod
    def backdrop(value: BackdropStyle) -> PresentationEffect: ...
    @staticmethod
    def lighting(value: LightingEnvironment) -> PresentationEffect: ...
    @staticmethod
    def display(value: DisplayTransform) -> PresentationEffect: ...
    @staticmethod
    def bloom(value: BloomStyle) -> PresentationEffect: ...
class EffectLayer:
    def __init__(self, effect: PresentationEffect) -> None: ...
    def with_weight(self, weight: float) -> EffectLayer: ...
    def with_priority(self, priority: int) -> EffectLayer: ...
class RenderProfile:
    @staticmethod
    def inspection() -> RenderProfile: ...
    @staticmethod
    def illustrative() -> RenderProfile: ...
    @staticmethod
    def cinematic() -> RenderProfile: ...
    def with_effect(self, effect: PresentationEffect) -> RenderProfile: ...
    def with_layer(self, layer: EffectLayer) -> RenderProfile: ...
    layer_count: int
class ResolvedRenderPlan:
    illustration: IllustrationStyle
    depth_of_field: DepthOfField | None
    motion_blur: MotionBlur | None
    backdrop: BackdropStyle
    lighting: LightingEnvironment
    display: DisplayTransform
    bloom: BloomStyle | None
class RenderSession:
    @staticmethod
    def capture(scene: Scene, camera: Camera, profile: RenderProfile) -> RenderSession: ...
    @staticmethod
    def from_json(source: str) -> RenderSession: ...
    def to_json(self) -> str: ...
    schema: int
    camera: Camera
    profile: RenderProfile

class ImageConfig:
    def __init__(self, width: int, height: int) -> None: ...
    @staticmethod
    def publication_4k() -> ImageConfig: ...
    width: int
    height: int
class EngineConfig:
    def __init__(self, width: int = ..., height: int = ..., mode: RenderMode | None = ..., profile: RenderProfile | None = ...) -> None: ...
    @staticmethod
    def default() -> EngineConfig: ...
    width: int
    height: int
    mode: RenderMode
    profile: RenderProfile
class Capabilities:
    max_storage_buffer_bytes: int
    max_texture_dim: int
    max_texture_dim_3d: int
    hardware_ray_tracing: bool
    mesh_shaders: bool
    bindless: bool
    timestamp_queries: bool
    subgroup_ops: bool
class Image:
    width: int
    height: int
    def numpy(self) -> NDArray[np.uint8]: ...
    def png_bytes(self) -> bytes: ...
class Engine:
    def __init__(self, config: EngineConfig | None = ...) -> None: ...
    def render(self, scene: Scene, camera: Camera) -> FrameOutcome: ...
    def render_image(self, scene: Scene, camera: Camera, width: int, height: int) -> NDArray[np.uint8]: ...
    def render_image_object(self, scene: Scene, camera: Camera, config: ImageConfig) -> Image: ...
    def resize(self, width: int, height: int) -> None: ...
    def set_render_mode(self, mode: RenderMode) -> None: ...
    def set_render_profile(self, profile: RenderProfile) -> None: ...
    def pick(self, x: int, y: int) -> Pick | None: ...
    render_mode: RenderMode
    render_profile: RenderProfile
    capabilities: Capabilities
    resolved_render_plan: ResolvedRenderPlan
class PickEntity:
    kind: str
    structure: EntityRef | None
    volume_segment: VolumeSegmentRef | None
class Pick:
    entity: PickEntity
    selection_indices: list[int]

class MolgfxError(Exception): ...
class CoreError(MolgfxError): ...
class GpuError(MolgfxError): ...
class SemanticError(MolgfxError): ...
class RenderError(MolgfxError): ...
